name: Check
on:
  push:
    branches: [ "main", "master" ]

  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest web.py
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test
        run: |
          pytest
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Lint
        uses: py-actions/flake8@v2


  archive:
      needs: [build, lint]
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3
        - name: Upload artifacts
          uses: actions/upload-artifact@v3
          with:
            path: ./

        - name: Archive
          run: |
            sudo apt-get update
            sudo apt-get install zip
            zip -r archive.zip *

        - name: Upload to gdrive
          uses: adityak74/google-drive-upload-git-action@main
          with:
            credentials: ${{ secrets.credentials }}
            filename: "archive.zip"
            folderId: ${{ secrets.folderId }}
            name: "documentation.zip"
            overwrite: "true"