name: Check
on:
  push:
    branches: [ "main", "master" ]

  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # This step checks out a copy of the repository.
      - uses: actions/checkout@v3
        # This step set up the correct Python version for the workflow runner,
        # depending on the project’s version
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint
        uses: py-actions/flake8@v2

      - name: Test
        run: |
          pytest

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ./